// import './instance'
// import './Lifecycle'
// import './databinding'
// import './computed'
// import './directve'
// import './component/define'
// import './component/extend'
// import './component/v-model'
// import './component/features'
import './component/render'
